Repository kyujin-cho/pixel-volte-patch, pull requests merged in 2023-05, with the labels that each got.

#131 fix: better zh_rCN string,remove resourceconfigurations as not needed
  .gitignore
  app/build.gradle
  app/src/main/res/values-zh-rCN/strings.xml
Labels: enhancement

#134 feat: add more toggles
  app/src/main/java/dev/bluehouse/enablevolte/Moder.kt
  app/src/main/java/dev/bluehouse/enablevolte/pages/Config.kt
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#43 Starting Shizuku without a PC(using wifi-debugging)
  README.en.md
Labels: documentation

#138 feat: add toggle to alter `KEY_ALLOW_ADDING_APNS_BOOL`
  app/src/main/java/dev/bluehouse/enablevolte/Components.kt
  app/src/main/java/dev/bluehouse/enablevolte/Moder.kt
  app/src/main/java/dev/bluehouse/enablevolte/pages/Config.kt
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#140 feat: add zh_rCN translation for `allow_adding_apns` literal
  app/src/main/res/values-zh-rCN/strings.xml
Labels: enhancement

#142 fix: app crash and eSIM index issue
  app/src/main/java/dev/bluehouse/enablevolte/Utils.kt
  app/src/main/java/dev/bluehouse/enablevolte/pages/Home.kt
Labels: bug, enhancement
