Repository kyujin-cho/pixel-volte-patch, pull requests merged in 2023-04, with the labels that each got.

#117 docs: Update compatibility-chart.en.md
  docs/compatibility-chart.en.md
Labels: documentation

#115 Fix: Unresolved reference and jvm target compatibility
  app/build.gradle
  app/src/main/java/dev/bluehouse/enablevolte/pages/Config.kt
Labels: bug

#122 chore: update copy for en strings
  app/src/main/res/values/strings.xml
Labels: enhancement
