Repository kyujin-cho/pixel-volte-patch, pull requests merged in 2024-01, with the labels that each got.

#231 fix: app crashing on latest beta
  .idea/misc.xml
  app/src/main/java/dev/bluehouse/enablevolte/Moder.kt
Labels: bug

#222 docs: add Jazz Pakistan to compatibility-chart
  docs/compatibility-chart.en.md
Labels: documentation

#235 ci: build and publish App Bundle
  .github/workflows/build-aab.yml
  .github/workflows/default.yml
Labels: enhancement

#246 feature: graceful shizuku binder handling
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/dev/bluehouse/enablevolte/HomeActivity.kt
  app/src/main/java/dev/bluehouse/enablevolte/Utils.kt
  app/src/main/java/dev/bluehouse/enablevolte/pages/Config.kt
  app/src/main/java/dev/bluehouse/enablevolte/pages/Home.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement
